### ISSUE TITLE
kdav does not sync correctly - 500 internal Server Error

### ISSUE THREAD

**Issue by boospy** [Kopano-dev/kdav#4]
Hello all,

we installed kdav on us kopano Server on UCS. It works with accounts with a few contacts, but with the central address book with over 400 contacts, we get an error. But don’t know what is to do, or where is the issue. Here is the end of the Log:

https://darkdevil.osit.cc/index.php/s/zc2YJFyEiXaAxTr

On some vcard i get this error in the webbrowser:

`<d:error><s:sabredav-version>3.2.2</s:sabredav-version><s:exception>Sabre\VObject\ParseException</s:exception><s:message>Invalid Mimedir file. Line starting at 10 did not follow iCalendar/vCard conventions</s:message></d:error>`

This is the last one in the list. So i think there is the error. But how i can identify what contact this is?

**Comment by fbartels** [comment]
Closing since this was already reported at https://forum.kopano.io/topic/2586/kdav-does-not-sync-correctly-500-internal-server-error
